//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TyrtyvshinGl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MovieForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovieForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TyrtyvshinGl.MovieForm", typeof(MovieForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle btndelete_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("btndelete.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Snap ITC, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font btndelete_Font {
            get {
                object obj = ResourceManager.GetObject("btndelete.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=124,Y=8}.
        /// </summary>
        internal static System.Drawing.Point btndelete_Location {
            get {
                object obj = ResourceManager.GetObject("btndelete.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding btndelete_Margin {
            get {
                object obj = ResourceManager.GetObject("btndelete.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=28}.
        /// </summary>
        internal static System.Drawing.Size btndelete_Size {
            get {
                object obj = ResourceManager.GetObject("btndelete.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int btndelete_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btndelete.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btndelete_Text {
            get {
                return ResourceManager.GetString("btndelete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle btnSave_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("btnSave.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=19,Y=8}.
        /// </summary>
        internal static System.Drawing.Point btnSave_Location {
            get {
                object obj = ResourceManager.GetObject("btnSave.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding btnSave_Margin {
            get {
                object obj = ResourceManager.GetObject("btnSave.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=28}.
        /// </summary>
        internal static System.Drawing.Size btnSave_Size {
            get {
                object obj = ResourceManager.GetObject("btnSave.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int btnSave_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnSave.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave_Text {
            get {
                return ResourceManager.GetString("btnSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle btnupdate_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("btnupdate.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=229,Y=8}.
        /// </summary>
        internal static System.Drawing.Point btnupdate_Location {
            get {
                object obj = ResourceManager.GetObject("btnupdate.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding btnupdate_Margin {
            get {
                object obj = ResourceManager.GetObject("btnupdate.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=28}.
        /// </summary>
        internal static System.Drawing.Size btnupdate_Size {
            get {
                object obj = ResourceManager.GetObject("btnupdate.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        internal static int btnupdate_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnupdate.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnupdate_Text {
            get {
                return ResourceManager.GetString("btnupdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1,Y=757}.
        /// </summary>
        internal static System.Drawing.Point button1_Location {
            get {
                object obj = ResourceManager.GetObject("button1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=833, Height=33}.
        /// </summary>
        internal static System.Drawing.Size button1_Size {
            get {
                object obj = ResourceManager.GetObject("button1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        internal static int button1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open current trailer in browser.
        /// </summary>
        internal static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle Clear_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("Clear.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=334,Y=9}.
        /// </summary>
        internal static System.Drawing.Point Clear_Location {
            get {
                object obj = ResourceManager.GetObject("Clear.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding Clear_Margin {
            get {
                object obj = ResourceManager.GetObject("Clear.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=28}.
        /// </summary>
        internal static System.Drawing.Size Clear_Size {
            get {
                object obj = ResourceManager.GetObject("Clear.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        internal static int Clear_TabIndex {
            get {
                object obj = ResourceManager.GetObject("Clear.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear_Text {
            get {
                return ResourceManager.GetString("Clear.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles dgvMovies_Anchor {
            get {
                object obj = ResourceManager.GetObject("dgvMovies.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=2,Y=17}.
        /// </summary>
        internal static System.Drawing.Point dgvMovies_Location {
            get {
                object obj = ResourceManager.GetObject("dgvMovies.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding dgvMovies_Margin {
            get {
                object obj = ResourceManager.GetObject("dgvMovies.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=1095, Height=382}.
        /// </summary>
        internal static System.Drawing.Size dgvMovies_Size {
            get {
                object obj = ResourceManager.GetObject("dgvMovies.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int dgvMovies_TabIndex {
            get {
                object obj = ResourceManager.GetObject("dgvMovies.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=635}.
        /// </summary>
        internal static System.Drawing.Point director_Location {
            get {
                object obj = ResourceManager.GetObject("director.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding director_Margin {
            get {
                object obj = ResourceManager.GetObject("director.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=128, Height=25}.
        /// </summary>
        internal static System.Drawing.Size director_Size {
            get {
                object obj = ResourceManager.GetObject("director.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int director_TabIndex {
            get {
                object obj = ResourceManager.GetObject("director.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=508,Y=42}.
        /// </summary>
        internal static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=1104, Height=827}.
        /// </summary>
        internal static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        internal static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=725}.
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding label1_Margin {
            get {
                object obj = ResourceManager.GetObject("label1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=23, Height=19}.
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=676}.
        /// </summary>
        internal static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding label2_Margin {
            get {
                object obj = ResourceManager.GetObject("label2.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=32, Height=19}.
        /// </summary>
        internal static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        internal static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label3_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label3.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=614}.
        /// </summary>
        internal static System.Drawing.Point label3_Location {
            get {
                object obj = ResourceManager.GetObject("label3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding label3_Margin {
            get {
                object obj = ResourceManager.GetObject("label3.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=56, Height=19}.
        /// </summary>
        internal static System.Drawing.Size label3_Size {
            get {
                object obj = ResourceManager.GetObject("label3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        internal static int label3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to director.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label4_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label4.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=551}.
        /// </summary>
        internal static System.Drawing.Point label4_Location {
            get {
                object obj = ResourceManager.GetObject("label4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding label4_Margin {
            get {
                object obj = ResourceManager.GetObject("label4.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=35, Height=19}.
        /// </summary>
        internal static System.Drawing.Size label4_Size {
            get {
                object obj = ResourceManager.GetObject("label4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        internal static int label4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label5_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label5.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=508,Y=8}.
        /// </summary>
        internal static System.Drawing.Point label5_Location {
            get {
                object obj = ResourceManager.GetObject("label5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=48, Height=19}.
        /// </summary>
        internal static System.Drawing.Size label5_Size {
            get {
                object obj = ResourceManager.GetObject("label5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        internal static int label5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=756}.
        /// </summary>
        internal static System.Drawing.Point movieID_Location {
            get {
                object obj = ResourceManager.GetObject("movieID.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding movieID_Margin {
            get {
                object obj = ResourceManager.GetObject("movieID.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=128, Height=25}.
        /// </summary>
        internal static System.Drawing.Size movieID_Size {
            get {
                object obj = ResourceManager.GetObject("movieID.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int movieID_TabIndex {
            get {
                object obj = ResourceManager.GetObject("movieID.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=43}.
        /// </summary>
        internal static System.Drawing.Point pctrbox1_Location {
            get {
                object obj = ResourceManager.GetObject("pctrbox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding pctrbox1_Margin {
            get {
                object obj = ResourceManager.GetObject("pctrbox1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=489, Height=488}.
        /// </summary>
        internal static System.Drawing.Size pctrbox1_Size {
            get {
                object obj = ResourceManager.GetObject("pctrbox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        internal static int pctrbox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pctrbox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=697}.
        /// </summary>
        internal static System.Drawing.Point title_Location {
            get {
                object obj = ResourceManager.GetObject("title.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding title_Margin {
            get {
                object obj = ResourceManager.GetObject("title.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=128, Height=25}.
        /// </summary>
        internal static System.Drawing.Size title_Size {
            get {
                object obj = ResourceManager.GetObject("title.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int title_TabIndex {
            get {
                object obj = ResourceManager.GetObject("title.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=562,Y=11}.
        /// </summary>
        internal static System.Drawing.Point txtsearch_Location {
            get {
                object obj = ResourceManager.GetObject("txtsearch.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=568, Height=25}.
        /// </summary>
        internal static System.Drawing.Size txtsearch_Size {
            get {
                object obj = ResourceManager.GetObject("txtsearch.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        internal static int txtsearch_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtsearch.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1,Y=405}.
        /// </summary>
        internal static System.Drawing.Point webView21_Location {
            get {
                object obj = ResourceManager.GetObject("webView21.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=833, Height=346}.
        /// </summary>
        internal static System.Drawing.Size webView21_Size {
            get {
                object obj = ResourceManager.GetObject("webView21.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        internal static int webView21_TabIndex {
            get {
                object obj = ResourceManager.GetObject("webView21.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=572}.
        /// </summary>
        internal static System.Drawing.Point year1_Location {
            get {
                object obj = ResourceManager.GetObject("year1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding year1_Margin {
            get {
                object obj = ResourceManager.GetObject("year1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=128, Height=25}.
        /// </summary>
        internal static System.Drawing.Size year1_Size {
            get {
                object obj = ResourceManager.GetObject("year1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int year1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("year1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
